### ISSUE TITLE
Padding bottom navbar

### ISSUE THREAD

**Issue by DaanKorver** [JustinLung/fitness-app#25]
Op safari op mobile heb je meer padding nodig bij de bottom maar op een ander device misschien niet. hiervoor zijn env variables voor in css speciaal voor safari.

voorbeeld
```css
nav {
    padding-bottom: calc(1em + env(safe-area-inset-bottom));
}
```
